In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Countries.csv")

In [3]:
df.shape

(194, 64)

In [4]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [7]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [15]:
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: object

In [19]:
df[df['population'] == df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [22]:
df[df['population'] == df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: object

In [23]:
df[df['population'] == df['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [31]:
df[df['democracy_score'] == df['democracy_score'].min()][['capital_city','democracy_score']]

            capital_city  democracy_score
3       Andorra la Vella              0.0
5           Saint John's              0.0
13            Bridgetown              0.0
16              Belmopan              0.0
23   Bandar Seri Begawan              0.0
48                Roseau              0.0
66          St. George's              0.0
87          South Tarawa              0.0
97                 Vaduz              0.0
103                 Malé              0.0
106               Majuro              0.0
110              Palikir              0.0
112               Monaco              0.0
119                Yaren              0.0
130            Ngerulmud              0.0
142                 Apia              0.0
143   City of San Marino              0.0
144             São Tomé              0.0
148             Victoria              0.0
153              Honiara              0.0
154            Mogadishu              0.0
156                 Juba              0.0
159           Basseterre              0.0
160             Castries              0.0
161            Kingstown              0.0
170               Nassau              0.0
174           Nuku'alofa              0.0
179             Funafuti              0.0
187            Port Vila              0.0

In [35]:
df.nsmallest(5,'democracy_score')[['country','democracy_score']]

                country  democracy_score
3               Andorra              0.0
5   Antigua and Barbuda              0.0
13             Barbados              0.0
16               Belize              0.0
23               Brunei              0.0

In [34]:
df.nlargest(5,'democracy_score')[['country','democracy_score']]

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

In [44]:
df['region'].nunique()

22

In [45]:
df['region'].value_counts()

region
Eastern Africa               17
Western Asia                 17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Northern Europe              10
Middle Africa                10
Eastern Europe               10
Western Europe                9
Southern Asia                 9
Central America               8
Northern Africa               6
Micronesia                    5
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [56]:
df[df['region'] == 'Eastern Europe'].shape[0]

10

In [60]:
(df['region'] == 'Eastern Europe').sum()

np.int64(10)

In [61]:
df[df['region'] == 'Eastern Europe']['country'].nunique()

10

In [64]:

df[df['population'] == df['population'].max()]['political_leader']

75    Narendra Modi
Name: political_leader, dtype: object

In [71]:
df.nlargest(2,'population').iloc[1][['country','political_leader']]

country                  China
political_leader    Xi Jinping
Name: 34, dtype: object

In [85]:
df[df['political_leader'].isna()]['country'].count()

np.int64(7)

In [95]:
df[df['region'] == 'Eastern Africa'].nlargest(1, 'population')[['country', 'population']]

     country  population
57  Ethiopia   123379924

In [93]:
df[df['region'] == 'Eastern Africa']['population'].max()

123379924